version: '3.8'
services:
  backend:
    container_name: mern-invoice-generator-backend
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - GST=${GST}
      - PROJECT_ID=${PROJECT_ID}
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mern-invoice-generator-mongo
    ports:
      - "27017:27017"
